In [ ]:
import numpy as np
from scipy.optimize import minimize
from plotly.subplots import make_subplots

In [ ]:
Pvap_data = np.loadtxt('WaterVaporPressure.csv', delimiter=',')

In [ ]:
T, Pexp = Pvap_data.T
log10Pexp = np.log10(Pexp)

In [ ]:
np.polyfit(1/T, log10Pexp, 1)

array([-2113.94814059,    10.63549233])

In [ ]:
def antoine_model(v):
  a,b,c = v
  model = 10**(a-(b/(T+c)))
  return np.sum((model - Pexp)**2)

In [ ]:
def log10_antoine(v):
  a,b,c = v
  model = a-(b/(T+c))
  return np.sum((model - log10Pexp)**2)

In [ ]:
ant_abc = minimize(antoine_model, ( 10.63549233, 2113.94814059, 0)).x

array([  10.4985072 , 2061.18822374,    5.34749591])

In [ ]:
ant10_abc = minimize(log10_antoine, (10.4985072, 2061.18822374, 5.34749591)).x

array([  10.2086922 , 1756.35674971,  -36.02766261])

In [ ]:
def antoine(v):
  a,b,c = v
  return 10**(a-(b/(T+c)))

In [ ]:
fig1 = make_subplots()
fig1.add_scatter(x = T, y = Pexp, mode = 'markers', name = 'Data')
fig1.add_scatter(x = T, y = antoine(ant_abc), mode = 'lines', name = 'Experimental')
fig1.add_scatter(x = T, y = antoine(ant10_abc), mode = 'lines', name = 'Logarithmic')
fig1.update_yaxes(type = 'log')

In [ ]:
A = np.c_[T, -log10Pexp, np.ones_like(T)]

In [ ]:
a,c,d = np.linalg.solve(A.T @ A, A.T @ (T*log10Pexp))

In [ ]:
b = -d + a*c

In [ ]:
b

1771.955100134423

In [ ]:
a,b,c

(10.227991116488935, 1771.955100134423, -34.378925933844585)